<?php
$content = array (
     $s . 'head',
     $d . 'getprice',
     $s . 'number1',
     //$s . 'torque',
     //$s . 'principles',
     //$s . 'example',
     //$s . 'whatcars',
     //$s . 'reserves',
     $s . 'products',
     $d . 'service',
     $d . 'equip',
     //$s . 'works',
     //$s . 'getright',
     $s . 'faq',
     //$s . 'morepower',
     //$s . 'stages',
     $d . 'wifi',
     $d . 'advantages',
     //$d . 'service_plus',
     $d . 'tune',
     $d . 'lab',
     //$d . 'consult',
     $d . 'map',
     $d . 'testimonials',
     $d . 'partners',
);