<?php
$content = array (
     $s . 'head',
     //$s . 'justline',
     //$s . 'whatfor',
     //$s . 'choose',
     //$s . 'twoway',
     $s . 'install',
     //$s . 'findout',
     //$d . 'advantages',
     $s . 'products',
     $d . 'service',
     //$d . 'service_plus',
     $d . 'equip',
     $d . 'tune',
     $d . 'lab',
     //$d . 'consult',
     //$d . 'works',
     //$s . 'stages',
     $d . 'wifi',
     $d . 'map',
     $d . 'partners',
     $s . 'testimonials',
);