<?php
$content = array (
     $s . 'head',
     $d . 'getprice',
     $s . 'number1',
     $s . 'install',
     $d . 'advantages',
     $s . 'products',
     //$s . 'whynot',
     $d . 'service',
     $d . 'equip',
     $d . 'tune',
     $d . 'lab',
     //$d . 'consult',
     //$s . 'getright',
     //$s . 'works',
     //$s . 'faq',
     //$s . 'findout',
     //$s . 'stages',
     $d . 'wifi',
     $d . 'map',
     $d . 'partners',
     $d . 'testimonials',
);